
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 29 15:13:32 IST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 2;
  public static final int EOFILE = 8;
  public static final int SEMI = 5;
  public static final int EQ = 11;
  public static final int EOF = 0;
  public static final int VAR = 3;
  public static final int error = 1;
  public static final int COM = 6;
  public static final int SPACE = 4;
  public static final int NEXTL = 7;
  public static final int FLOAT = 10;
  public static final int FLOATNO = 9;
}

