
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 22 11:06:17 IST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 7;
  public static final int NEXTL = 8;
  public static final int PLUS = 3;
  public static final int RPAREN = 21;
  public static final int INT = 13;
  public static final int DCHAR = 14;
  public static final int EQUAL = 17;
  public static final int CHAR = 10;
  public static final int SEMI = 2;
  public static final int COM = 11;
  public static final int LPAREN = 20;
  public static final int SPACE = 12;
  public static final int FLOAT = 16;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int STR = 18;
  public static final int EOFILE = 9;
  public static final int UMINUS = 19;
  public static final int DOUBLE = 15;
}

