
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 29 04:59:45 IST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 7;
  public static final int LTE = 35;
  public static final int MULT = 18;
  public static final int CONST = 21;
  public static final int CHAR = 10;
  public static final int EQUALS = 12;
  public static final int INTEGER = 20;
  public static final int NOTEQUAL = 33;
  public static final int SEMI = 4;
  public static final int CONTINUE = 28;
  public static final int INT = 2;
  public static final int ARRAY = 23;
  public static final int FOR = 46;
  public static final int MINUS = 17;
  public static final int LT = 36;
  public static final int EQUALTO = 32;
  public static final int FLOATPOINT = 13;
  public static final int NIL = 15;
  public static final int COMMA = 5;
  public static final int FI = 42;
  public static final int DIV = 19;
  public static final int STRINGARRAY = 24;
  public static final int NEXT = 11;
  public static final int PLUS = 16;
  public static final int CB = 45;
  public static final int IF = 40;
  public static final int CLOSEBR = 39;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int RETURN = 29;
  public static final int OB = 44;
  public static final int error = 1;
  public static final int BREAK = 27;
  public static final int GTE = 34;
  public static final int STRINGVAL = 22;
  public static final int EOFILE = 8;
  public static final int READ = 31;
  public static final int TO = 48;
  public static final int WHILE = 41;
  public static final int OPENBR = 38;
  public static final int FLOAT = 9;
  public static final int END = 43;
  public static final int ARRAYID = 26;
  public static final int STRING = 3;
  public static final int GT = 37;
  public static final int VAR = 14;
  public static final int DO = 47;
  public static final int PRINT = 30;
  public static final int IDENTIFIER = 25;
}

